# Form implementation generated from reading ui file '/Users/pinxun/Documents/MindX/PTA/PTA07/TriCuong/python-app/ui/mainwindow.ui'
#
# Created by: PyQt6 UI code generator 6.8.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1100, 717)
        MainWindow.setStyleSheet("background-color:rgb(51, 107, 135)")
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.stackedWidget = QtWidgets.QStackedWidget(parent=self.centralwidget)
        self.stackedWidget.setGeometry(QtCore.QRect(110, 50, 991, 621))
        self.stackedWidget.setAcceptDrops(False)
        self.stackedWidget.setAutoFillBackground(False)
        self.stackedWidget.setStyleSheet("background-color:rgb(144, 175, 197)")
        self.stackedWidget.setObjectName("stackedWidget")
        self.page_tintuc = QtWidgets.QWidget()
        self.page_tintuc.setObjectName("page_tintuc")
        self.timeEdit = QtWidgets.QTimeEdit(parent=self.page_tintuc)
        self.timeEdit.setGeometry(QtCore.QRect(0, 10, 118, 26))
        self.timeEdit.setStyleSheet("background-color:rgb(255, 255, 255)")
        self.timeEdit.setObjectName("timeEdit")
        self.verticalScrollBar = QtWidgets.QScrollBar(parent=self.page_tintuc)
        self.verticalScrollBar.setGeometry(QtCore.QRect(990, 20, 16, 561))
        self.verticalScrollBar.setOrientation(QtCore.Qt.Orientation.Vertical)
        self.verticalScrollBar.setObjectName("verticalScrollBar")
        self.label_3 = QtWidgets.QLabel(parent=self.page_tintuc)
        self.label_3.setEnabled(True)
        self.label_3.setGeometry(QtCore.QRect(20, 50, 961, 91))
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI Semibold")
        font.setBold(True)
        self.label_3.setFont(font)
        self.label_3.setMouseTracking(False)
        self.label_3.setTabletTracking(False)
        self.label_3.setAcceptDrops(False)
        self.label_3.setAccessibleDescription("")
        self.label_3.setAutoFillBackground(False)
        self.label_3.setStyleSheet("background-color:rgb(0, 0, 165);\n"
"border-radius: 10px;\n"
"color:rgb(255, 255, 255)")
        self.label_3.setScaledContents(False)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(parent=self.page_tintuc)
        self.label_4.setEnabled(True)
        self.label_4.setGeometry(QtCore.QRect(20, 170, 961, 91))
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI Semibold")
        font.setBold(True)
        font.setItalic(False)
        font.setUnderline(False)
        font.setStrikeOut(False)
        self.label_4.setFont(font)
        self.label_4.setMouseTracking(False)
        self.label_4.setTabletTracking(False)
        self.label_4.setAcceptDrops(False)
        self.label_4.setAccessibleDescription("")
        self.label_4.setAutoFillBackground(False)
        self.label_4.setStyleSheet("background-color:rgb(0, 0, 165);\n"
"border-radius: 10px;\n"
"color:rgb(255, 255, 255)")
        self.label_4.setScaledContents(False)
        self.label_4.setObjectName("label_4")
        self.label_6 = QtWidgets.QLabel(parent=self.page_tintuc)
        self.label_6.setEnabled(True)
        self.label_6.setGeometry(QtCore.QRect(20, 410, 961, 91))
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI Semibold")
        font.setBold(True)
        font.setItalic(False)
        font.setUnderline(False)
        font.setStrikeOut(False)
        self.label_6.setFont(font)
        self.label_6.setMouseTracking(False)
        self.label_6.setTabletTracking(False)
        self.label_6.setAcceptDrops(False)
        self.label_6.setAccessibleDescription("")
        self.label_6.setAutoFillBackground(False)
        self.label_6.setStyleSheet("background-color:rgb(0, 0, 165);\n"
"border-radius: 10px;\n"
"color:rgb(255, 255, 255)")
        self.label_6.setScaledContents(False)
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(parent=self.page_tintuc)
        self.label_7.setEnabled(True)
        self.label_7.setGeometry(QtCore.QRect(20, 290, 961, 91))
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI Semibold")
        font.setBold(True)
        font.setItalic(False)
        font.setUnderline(False)
        font.setStrikeOut(False)
        self.label_7.setFont(font)
        self.label_7.setMouseTracking(False)
        self.label_7.setTabletTracking(False)
        self.label_7.setAcceptDrops(False)
        self.label_7.setAccessibleDescription("")
        self.label_7.setAutoFillBackground(False)
        self.label_7.setStyleSheet("background-color:rgb(0, 0, 165);\n"
"border-radius: 10px;\n"
"color:rgb(255, 255, 255)")
        self.label_7.setScaledContents(False)
        self.label_7.setObjectName("label_7")
        self.dateEdit = QtWidgets.QDateEdit(parent=self.page_tintuc)
        self.dateEdit.setGeometry(QtCore.QRect(120, 10, 110, 26))
        self.dateEdit.setStyleSheet("background-color:rgb(255, 255, 255)")
        self.dateEdit.setObjectName("dateEdit")
        self.dateEdit_2 = QtWidgets.QDateEdit(parent=self.page_tintuc)
        self.dateEdit_2.setGeometry(QtCore.QRect(860, 110, 110, 26))
        self.dateEdit_2.setStyleSheet("background-color:rgb(255, 255, 255)\n"
"")
        self.dateEdit_2.setDateTime(QtCore.QDateTime(QtCore.QDate(2024, 12, 11), QtCore.QTime(11, 38, 0)))
        self.dateEdit_2.setTime(QtCore.QTime(11, 38, 0))
        self.dateEdit_2.setObjectName("dateEdit_2")
        self.dateEdit_3 = QtWidgets.QDateEdit(parent=self.page_tintuc)
        self.dateEdit_3.setGeometry(QtCore.QRect(860, 230, 110, 26))
        self.dateEdit_3.setStyleSheet("background-color:rgb(255, 255, 255)")
        self.dateEdit_3.setDateTime(QtCore.QDateTime(QtCore.QDate(2024, 8, 11), QtCore.QTime(11, 38, 0)))
        self.dateEdit_3.setTime(QtCore.QTime(11, 38, 0))
        self.dateEdit_3.setObjectName("dateEdit_3")
        self.dateEdit_4 = QtWidgets.QDateEdit(parent=self.page_tintuc)
        self.dateEdit_4.setGeometry(QtCore.QRect(860, 350, 110, 26))
        self.dateEdit_4.setStyleSheet("background-color:rgb(255, 255, 255)\n"
"\n"
"")
        self.dateEdit_4.setDateTime(QtCore.QDateTime(QtCore.QDate(2024, 2, 11), QtCore.QTime(11, 38, 0)))
        self.dateEdit_4.setTime(QtCore.QTime(11, 38, 0))
        self.dateEdit_4.setObjectName("dateEdit_4")
        self.dateEdit_5 = QtWidgets.QDateEdit(parent=self.page_tintuc)
        self.dateEdit_5.setGeometry(QtCore.QRect(860, 470, 110, 26))
        self.dateEdit_5.setStyleSheet("background-color:rgb(255, 255, 255)")
        self.dateEdit_5.setDateTime(QtCore.QDateTime(QtCore.QDate(2024, 12, 10), QtCore.QTime(11, 38, 0)))
        self.dateEdit_5.setTime(QtCore.QTime(11, 38, 0))
        self.dateEdit_5.setMaximumDateTime(QtCore.QDateTime(QtCore.QDate(9999, 12, 8), QtCore.QTime(7, 59, 59)))
        self.dateEdit_5.setObjectName("dateEdit_5")
        self.label_16 = QtWidgets.QLabel(parent=self.page_tintuc)
        self.label_16.setEnabled(True)
        self.label_16.setGeometry(QtCore.QRect(20, 530, 961, 91))
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI Semibold")
        font.setBold(True)
        font.setItalic(False)
        font.setUnderline(False)
        font.setStrikeOut(False)
        self.label_16.setFont(font)
        self.label_16.setMouseTracking(False)
        self.label_16.setTabletTracking(False)
        self.label_16.setAcceptDrops(False)
        self.label_16.setAccessibleDescription("")
        self.label_16.setAutoFillBackground(False)
        self.label_16.setStyleSheet("background-color:rgb(0, 0, 165);\n"
"border-radius: 10px;\n"
"color:rgb(255, 255, 255)")
        self.label_16.setScaledContents(False)
        self.label_16.setObjectName("label_16")
        self.dateEdit_6 = QtWidgets.QDateEdit(parent=self.page_tintuc)
        self.dateEdit_6.setGeometry(QtCore.QRect(860, 590, 110, 26))
        self.dateEdit_6.setStyleSheet("background-color:rgb(255, 255, 255)")
        self.dateEdit_6.setDateTime(QtCore.QDateTime(QtCore.QDate(2024, 12, 10), QtCore.QTime(11, 38, 0)))
        self.dateEdit_6.setTime(QtCore.QTime(11, 38, 0))
        self.dateEdit_6.setMaximumDateTime(QtCore.QDateTime(QtCore.QDate(9999, 12, 8), QtCore.QTime(0, 59, 59)))
        self.dateEdit_6.setObjectName("dateEdit_6")
        self.stackedWidget.addWidget(self.page_tintuc)
        self.page_applications = QtWidgets.QWidget()
        self.page_applications.setStyleSheet("background-color: rgb(144, 175, 197);")
        self.page_applications.setObjectName("page_applications")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.page_applications)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.btn_new_application = QtWidgets.QPushButton(parent=self.page_applications)
        self.btn_new_application.setStyleSheet("background-color: rgb(0, 0, 165);\n"
"border-radius: 10px;\n"
"color: rgb(255, 255, 255);\n"
"padding: 10px;\n"
"font-weight: bold;")
        self.btn_new_application.setObjectName("btn_new_application")
        self.horizontalLayout_3.addWidget(self.btn_new_application)
        self.btn_edit_application = QtWidgets.QPushButton(parent=self.page_applications)
        self.btn_edit_application.setStyleSheet("background-color: rgb(0, 0, 165);\n"
"border-radius: 10px;\n"
"color: rgb(255, 255, 255);\n"
"padding: 10px;\n"
"font-weight: bold;")
        self.btn_edit_application.setObjectName("btn_edit_application")
        self.horizontalLayout_3.addWidget(self.btn_edit_application)
        self.btn_delete_application = QtWidgets.QPushButton(parent=self.page_applications)
        self.btn_delete_application.setStyleSheet("background-color: rgb(0, 0, 165);\n"
"border-radius: 10px;\n"
"color: rgb(255, 255, 255);\n"
"padding: 10px;\n"
"font-weight: bold;")
        self.btn_delete_application.setObjectName("btn_delete_application")
        self.horizontalLayout_3.addWidget(self.btn_delete_application)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem)
        self.verticalLayout_3.addLayout(self.horizontalLayout_3)
        self.applications_table = QtWidgets.QTableWidget(parent=self.page_applications)
        self.applications_table.setStyleSheet("\n"
"QTableWidget {\n"
"    background-color: rgb(144, 175, 197);\n"
"    color: black;\n"
"    gridline-color: #2c5a73;\n"
"    border: none;\n"
"}\n"
"\n"
"QTableWidget::item {\n"
"    padding: 8px;\n"
"    border: none;\n"
"}\n"
"\n"
"QTableWidget::item:selected {\n"
"    background-color: #336b87;\n"
"    color: white;\n"
"}\n"
"\n"
"QHeaderView::section {\n"
"    background-color: #336b87;\n"
"    color: white;\n"
"    padding: 10px;\n"
"    border: none;\n"
"    font-weight: bold;\n"
"    text-align: center;\n"
"}\n"
"\n"
"QTableWidget QScrollBar:vertical {\n"
"    background-color: rgb(144, 175, 197);\n"
"    width: 12px;\n"
"    margin: 0px;\n"
"}\n"
"\n"
"QTableWidget QScrollBar::handle:vertical {\n"
"    background-color: #336b87;\n"
"    border-radius: 6px;\n"
"    min-height: 20px;\n"
"}\n"
"\n"
"QTableWidget QScrollBar::add-line:vertical,\n"
"QTableWidget QScrollBar::sub-line:vertical {\n"
"    height: 0px;\n"
"}\n"
"\n"
"QTableWidget QScrollBar:horizontal {\n"
"    background-color: rgb(144, 175, 197);\n"
"    height: 12px;\n"
"    margin: 0px;\n"
"}\n"
"\n"
"QTableWidget QScrollBar::handle:horizontal {\n"
"    background-color: #336b87;\n"
"    border-radius: 6px;\n"
"    min-width: 20px;\n"
"}\n"
"\n"
"QTableWidget QScrollBar::add-line:horizontal,\n"
"QTableWidget QScrollBar::sub-line:horizontal {\n"
"    width: 0px;\n"
"}\n"
"         ")
        self.applications_table.setAlternatingRowColors(True)
        self.applications_table.setSelectionMode(QtWidgets.QAbstractItemView.SelectionMode.SingleSelection)
        self.applications_table.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectionBehavior.SelectRows)
        self.applications_table.setObjectName("applications_table")
        self.applications_table.setColumnCount(0)
        self.applications_table.setRowCount(0)
        self.verticalLayout_3.addWidget(self.applications_table)
        self.stackedWidget.addWidget(self.page_applications)
        self.lienhe = QtWidgets.QWidget()
        self.lienhe.setObjectName("lienhe")
        self.label_75 = QtWidgets.QLabel(parent=self.lienhe)
        self.label_75.setGeometry(QtCore.QRect(30, 30, 621, 31))
        font = QtGui.QFont()
        font.setBold(False)
        self.label_75.setFont(font)
        self.label_75.setStyleSheet("background-color:rgb(0, 0, 165);\n"
"border-radius: 10px;\n"
"color:rgb(255, 255, 255)")
        self.label_75.setObjectName("label_75")
        self.label_76 = QtWidgets.QLabel(parent=self.lienhe)
        self.label_76.setGeometry(QtCore.QRect(30, 90, 621, 31))
        self.label_76.setStyleSheet("background-color:rgb(0, 0, 165);\n"
"border-radius: 10px;\n"
"color:rgb(255, 255, 255)")
        self.label_76.setObjectName("label_76")
        self.label_77 = QtWidgets.QLabel(parent=self.lienhe)
        self.label_77.setGeometry(QtCore.QRect(30, 290, 621, 31))
        self.label_77.setStyleSheet("background-color:rgb(0, 0, 165);\n"
"border-radius: 10px;\n"
"color:rgb(255, 255, 255)")
        self.label_77.setObjectName("label_77")
        self.label_78 = QtWidgets.QLabel(parent=self.lienhe)
        self.label_78.setGeometry(QtCore.QRect(30, 150, 621, 31))
        self.label_78.setStyleSheet("background-color:rgb(0, 0, 165);\n"
"border-radius: 10px;\n"
"color:rgb(255, 255, 255)")
        self.label_78.setObjectName("label_78")
        self.label_79 = QtWidgets.QLabel(parent=self.lienhe)
        self.label_79.setGeometry(QtCore.QRect(30, 350, 621, 31))
        self.label_79.setStyleSheet("background-color:rgb(0, 0, 165);\n"
"border-radius: 10px;\n"
"color:rgb(255, 255, 255)")
        self.label_79.setObjectName("label_79")
        self.label_80 = QtWidgets.QLabel(parent=self.lienhe)
        self.label_80.setGeometry(QtCore.QRect(30, 220, 621, 31))
        self.label_80.setStyleSheet("background-color:rgb(0, 0, 165);\n"
"border-radius: 10px;\n"
"color:rgb(255, 255, 255)")
        self.label_80.setObjectName("label_80")
        self.label_81 = QtWidgets.QLabel(parent=self.lienhe)
        self.label_81.setGeometry(QtCore.QRect(30, 470, 621, 31))
        self.label_81.setStyleSheet("background-color:rgb(0, 0, 165);\n"
"border-radius: 10px;\n"
"color:rgb(255, 255, 255)")
        self.label_81.setObjectName("label_81")
        self.label_82 = QtWidgets.QLabel(parent=self.lienhe)
        self.label_82.setGeometry(QtCore.QRect(30, 410, 621, 31))
        self.label_82.setStyleSheet("background-color:rgb(0, 0, 165);\n"
"border-radius: 10px;\n"
"color:rgb(255, 255, 255)")
        self.label_82.setObjectName("label_82")
        self.label_83 = QtWidgets.QLabel(parent=self.lienhe)
        self.label_83.setGeometry(QtCore.QRect(30, 520, 621, 31))
        self.label_83.setStyleSheet("background-color:rgb(0, 0, 165);\n"
"border-radius: 10px;\n"
"color:rgb(255, 255, 255)")
        self.label_83.setObjectName("label_83")
        self.label_84 = QtWidgets.QLabel(parent=self.lienhe)
        self.label_84.setGeometry(QtCore.QRect(30, 570, 621, 31))
        self.label_84.setStyleSheet("background-color:rgb(0, 0, 165);\n"
"border-radius: 10px;\n"
"color:rgb(255, 255, 255)")
        self.label_84.setObjectName("label_84")
        self.verticalScrollBar_4 = QtWidgets.QScrollBar(parent=self.lienhe)
        self.verticalScrollBar_4.setGeometry(QtCore.QRect(990, 20, 16, 591))
        self.verticalScrollBar_4.setOrientation(QtCore.Qt.Orientation.Vertical)
        self.verticalScrollBar_4.setObjectName("verticalScrollBar_4")
        self.verticalScrollBar_2 = QtWidgets.QScrollBar(parent=self.lienhe)
        self.verticalScrollBar_2.setGeometry(QtCore.QRect(970, 30, 16, 471))
        self.verticalScrollBar_2.setOrientation(QtCore.Qt.Orientation.Vertical)
        self.verticalScrollBar_2.setObjectName("verticalScrollBar_2")
        self.stackedWidget.addWidget(self.lienhe)
        self.setting = QtWidgets.QWidget()
        self.setting.setObjectName("setting")
        self.txt_name = QtWidgets.QLineEdit(parent=self.setting)
        self.txt_name.setGeometry(QtCore.QRect(340, 160, 261, 51))
        font = QtGui.QFont()
        font.setFamily("SimSun")
        font.setPointSize(-1)
        self.txt_name.setFont(font)
        self.txt_name.setStyleSheet("border: none;\n"
"    border-bottom: 1px solid #000; /* Black underline */\n"
"    font-size: 14px;\n"
"    padding: 5px;\n"
"color: white;")
        self.txt_name.setText("")
        self.txt_name.setFrame(False)
        self.txt_name.setEchoMode(QtWidgets.QLineEdit.EchoMode.Normal)
        self.txt_name.setDragEnabled(False)
        self.txt_name.setReadOnly(False)
        self.txt_name.setClearButtonEnabled(False)
        self.txt_name.setObjectName("txt_name")
        self.btn_update_info = QtWidgets.QPushButton(parent=self.setting)
        self.btn_update_info.setGeometry(QtCore.QRect(340, 500, 261, 51))
        self.btn_update_info.setStyleSheet("background-color: #000; /* Black background */\n"
"    color: #fff; /* White text */\n"
"    font-size: 14px; /* Adjust text size */\n"
"    border: none; /* Remove borders */\n"
"    border-radius: 20px; /* Rounded corners */\n"
"    padding: 10px 20px; /* Add padding for a larger button */\n"
"    text-align: center; /* Center the text */")
        self.btn_update_info.setObjectName("btn_update_info")
        self.txt_email = QtWidgets.QLineEdit(parent=self.setting)
        self.txt_email.setGeometry(QtCore.QRect(340, 240, 261, 51))
        font = QtGui.QFont()
        font.setFamily("SimSun")
        font.setPointSize(-1)
        self.txt_email.setFont(font)
        self.txt_email.setStyleSheet("border: none;\n"
"    border-bottom: 1px solid #000; /* Black underline */\n"
"    font-size: 14px;\n"
"    padding: 5px;\n"
"color: white;")
        self.txt_email.setText("")
        self.txt_email.setFrame(False)
        self.txt_email.setEchoMode(QtWidgets.QLineEdit.EchoMode.Normal)
        self.txt_email.setDragEnabled(False)
        self.txt_email.setReadOnly(False)
        self.txt_email.setClearButtonEnabled(False)
        self.txt_email.setObjectName("txt_email")
        self.btn_avatar = QtWidgets.QPushButton(parent=self.setting)
        self.btn_avatar.setGeometry(QtCore.QRect(350, 10, 201, 141))
        self.btn_avatar.setAutoFillBackground(False)
        self.btn_avatar.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("/Users/pinxun/Documents/MindX/PTA/PTA07/TriCuong/python-app/ui/../img/account-information.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.btn_avatar.setIcon(icon)
        self.btn_avatar.setIconSize(QtCore.QSize(150, 150))
        self.btn_avatar.setCheckable(False)
        self.btn_avatar.setChecked(False)
        self.btn_avatar.setAutoRepeat(False)
        self.btn_avatar.setAutoExclusive(False)
        self.btn_avatar.setAutoDefault(False)
        self.btn_avatar.setDefault(False)
        self.btn_avatar.setFlat(True)
        self.btn_avatar.setObjectName("btn_avatar")
        self.d_dob = QtWidgets.QDateEdit(parent=self.setting)
        self.d_dob.setGeometry(QtCore.QRect(340, 330, 261, 51))
        self.d_dob.setStyleSheet("border: none;\n"
"    border-bottom: 1px solid #000; /* Black underline */\n"
"    font-size: 14px;\n"
"    padding: 5px;\n"
"color: white;")
        self.d_dob.setObjectName("d_dob")
        self.cb_gender = QtWidgets.QComboBox(parent=self.setting)
        self.cb_gender.setGeometry(QtCore.QRect(340, 420, 261, 41))
        self.cb_gender.setStyleSheet("border: none;\n"
"    border-bottom: 1px solid #000; /* Black underline */\n"
"    font-size: 14px;\n"
"    padding: 5px;\n"
"color: white;")
        self.cb_gender.setObjectName("cb_gender")
        self.cb_gender.addItem("")
        self.cb_gender.addItem("")
        self.cb_gender.addItem("")
        self.stackedWidget.addWidget(self.setting)
        self.page_chucnang = QtWidgets.QWidget()
        self.page_chucnang.setObjectName("page_chucnang")
        self.label = QtWidgets.QLabel(parent=self.page_chucnang)
        self.label.setGeometry(QtCore.QRect(20, 10, 371, 41))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        font.setBold(True)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(parent=self.page_chucnang)
        self.label_2.setGeometry(QtCore.QRect(20, 170, 121, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.label_5 = QtWidgets.QLabel(parent=self.page_chucnang)
        self.label_5.setGeometry(QtCore.QRect(20, 340, 221, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.label_8 = QtWidgets.QLabel(parent=self.page_chucnang)
        self.label_8.setGeometry(QtCore.QRect(20, 470, 271, 20))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.label_10 = QtWidgets.QLabel(parent=self.page_chucnang)
        self.label_10.setGeometry(QtCore.QRect(250, 90, 81, 41))
        self.label_10.setStyleSheet("background-color:rgb(0, 0, 165);\n"
"border-radius: 10px;\n"
"color:rgb(255, 255, 255)")
        self.label_10.setObjectName("label_10")
        self.label_11 = QtWidgets.QLabel(parent=self.page_chucnang)
        self.label_11.setGeometry(QtCore.QRect(510, 250, 111, 41))
        self.label_11.setStyleSheet("background-color:rgb(0, 0, 165);\n"
"border-radius: 10px;\n"
"color:rgb(255, 255, 255)")
        self.label_11.setObjectName("label_11")
        self.label_12 = QtWidgets.QLabel(parent=self.page_chucnang)
        self.label_12.setGeometry(QtCore.QRect(220, 250, 161, 41))
        self.label_12.setStyleSheet("background-color:rgb(0, 0, 165);\n"
"border-radius: 10px;\n"
"color:rgb(255, 255, 255);\n"
" text-align: center")
        self.label_12.setObjectName("label_12")
        self.label_14 = QtWidgets.QLabel(parent=self.page_chucnang)
        self.label_14.setGeometry(QtCore.QRect(40, 420, 71, 41))
        self.label_14.setStyleSheet("background-color:rgb(0, 0, 165);\n"
"border-radius: 10px;\n"
"color:rgb(255, 255, 255)")
        self.label_14.setObjectName("label_14")
        self.label_43 = QtWidgets.QLabel(parent=self.page_chucnang)
        self.label_43.setGeometry(QtCore.QRect(10, 540, 131, 41))
        self.label_43.setStyleSheet("background-color:rgb(0, 0, 165);\n"
"border-radius: 10px;\n"
"color:rgb(255, 255, 255)")
        self.label_43.setObjectName("label_43")
        self.label_44 = QtWidgets.QLabel(parent=self.page_chucnang)
        self.label_44.setGeometry(QtCore.QRect(260, 540, 101, 41))
        self.label_44.setStyleSheet("background-color:rgb(0, 0, 165);\n"
"border-radius: 10px;\n"
"color:rgb(255, 255, 255)")
        self.label_44.setObjectName("label_44")
        self.label_45 = QtWidgets.QLabel(parent=self.page_chucnang)
        self.label_45.setGeometry(QtCore.QRect(530, 540, 61, 41))
        self.label_45.setStyleSheet("background-color:rgb(0, 0, 165);\n"
"border-radius: 10px;\n"
"color:rgb(255, 255, 255);\n"
"    text-align: center; /* Center the text */")
        self.label_45.setObjectName("label_45")
        self.label_46 = QtWidgets.QLabel(parent=self.page_chucnang)
        self.label_46.setGeometry(QtCore.QRect(60, 50, 41, 31))
        self.label_46.setAccessibleDescription("")
        self.label_46.setAutoFillBackground(False)
        self.label_46.setStyleSheet("")
        self.label_46.setText("")
        self.label_46.setPixmap(QtGui.QPixmap("/Users/pinxun/Documents/MindX/PTA/PTA07/TriCuong/python-app/ui/../img/weekend.png"))
        self.label_46.setScaledContents(True)
        self.label_46.setWordWrap(False)
        self.label_46.setOpenExternalLinks(False)
        self.label_46.setObjectName("label_46")
        self.label_48 = QtWidgets.QLabel(parent=self.page_chucnang)
        self.label_48.setGeometry(QtCore.QRect(270, 50, 41, 31))
        self.label_48.setStyleSheet("")
        self.label_48.setText("")
        self.label_48.setPixmap(QtGui.QPixmap("/Users/pinxun/Documents/MindX/PTA/PTA07/TriCuong/python-app/ui/../img/checklist.png"))
        self.label_48.setScaledContents(True)
        self.label_48.setObjectName("label_48")
        self.label_49 = QtWidgets.QLabel(parent=self.page_chucnang)
        self.label_49.setGeometry(QtCore.QRect(50, 210, 41, 31))
        self.label_49.setStyleSheet("")
        self.label_49.setText("")
        self.label_49.setPixmap(QtGui.QPixmap("/Users/pinxun/Documents/MindX/PTA/PTA07/TriCuong/python-app/ui/../img/weekend.png"))
        self.label_49.setScaledContents(True)
        self.label_49.setObjectName("label_49")
        self.label_69 = QtWidgets.QLabel(parent=self.page_chucnang)
        self.label_69.setGeometry(QtCore.QRect(280, 210, 41, 31))
        self.label_69.setStyleSheet("")
        self.label_69.setText("")
        self.label_69.setPixmap(QtGui.QPixmap("/Users/pinxun/Documents/MindX/PTA/PTA07/TriCuong/python-app/ui/../img/checklist.png"))
        self.label_69.setScaledContents(True)
        self.label_69.setObjectName("label_69")
        self.label_70 = QtWidgets.QLabel(parent=self.page_chucnang)
        self.label_70.setGeometry(QtCore.QRect(540, 210, 41, 31))
        self.label_70.setStyleSheet("")
        self.label_70.setText("")
        self.label_70.setPixmap(QtGui.QPixmap("/Users/pinxun/Documents/MindX/PTA/PTA07/TriCuong/python-app/ui/../img/checklist.png"))
        self.label_70.setScaledContents(True)
        self.label_70.setObjectName("label_70")
        self.label_71 = QtWidgets.QLabel(parent=self.page_chucnang)
        self.label_71.setGeometry(QtCore.QRect(60, 380, 31, 31))
        self.label_71.setText("")
        self.label_71.setPixmap(QtGui.QPixmap("/Users/pinxun/Documents/MindX/PTA/PTA07/TriCuong/python-app/ui/../img/front-of-bus.png"))
        self.label_71.setScaledContents(True)
        self.label_71.setObjectName("label_71")
        self.label_72 = QtWidgets.QLabel(parent=self.page_chucnang)
        self.label_72.setGeometry(QtCore.QRect(60, 500, 31, 31))
        self.label_72.setText("")
        self.label_72.setPixmap(QtGui.QPixmap("/Users/pinxun/Documents/MindX/PTA/PTA07/TriCuong/python-app/ui/../img/account-information.png"))
        self.label_72.setScaledContents(True)
        self.label_72.setObjectName("label_72")
        self.label_73 = QtWidgets.QLabel(parent=self.page_chucnang)
        self.label_73.setGeometry(QtCore.QRect(290, 500, 41, 31))
        self.label_73.setText("")
        self.label_73.setPixmap(QtGui.QPixmap("/Users/pinxun/Documents/MindX/PTA/PTA07/TriCuong/python-app/ui/../img/interrogation-mark.png"))
        self.label_73.setScaledContents(True)
        self.label_73.setObjectName("label_73")
        self.label_74 = QtWidgets.QLabel(parent=self.page_chucnang)
        self.label_74.setGeometry(QtCore.QRect(540, 500, 41, 31))
        self.label_74.setText("")
        self.label_74.setPixmap(QtGui.QPixmap("/Users/pinxun/Documents/MindX/PTA/PTA07/TriCuong/python-app/ui/../img/weekend.png"))
        self.label_74.setScaledContents(True)
        self.label_74.setObjectName("label_74")
        self.label_64 = QtWidgets.QLabel(parent=self.page_chucnang)
        self.label_64.setGeometry(QtCore.QRect(850, 20, 111, 111))
        self.label_64.setStyleSheet("background-color:rgb(0, 0, 0)")
        self.label_64.setText("")
        self.label_64.setPixmap(QtGui.QPixmap("/Users/pinxun/Documents/MindX/PTA/PTA07/TriCuong/python-app/ui/../img/tải xuống.png"))
        self.label_64.setScaledContents(True)
        self.label_64.setWordWrap(False)
        self.label_64.setOpenExternalLinks(False)
        self.label_64.setObjectName("label_64")
        self.label_15 = QtWidgets.QLabel(parent=self.page_chucnang)
        self.label_15.setGeometry(QtCore.QRect(270, 420, 71, 41))
        self.label_15.setStyleSheet("background-color:rgb(0, 0, 165);\n"
"border-radius: 10px;\n"
"color:rgb(255, 255, 255)")
        self.label_15.setObjectName("label_15")
        self.label_85 = QtWidgets.QLabel(parent=self.page_chucnang)
        self.label_85.setGeometry(QtCore.QRect(280, 370, 41, 41))
        self.label_85.setText("")
        self.label_85.setPixmap(QtGui.QPixmap("/Users/pinxun/Documents/MindX/PTA/PTA07/TriCuong/python-app/ui/../img/hot-pot.png"))
        self.label_85.setScaledContents(True)
        self.label_85.setObjectName("label_85")
        self.btn_schedule = QtWidgets.QPushButton(parent=self.page_chucnang)
        self.btn_schedule.setGeometry(QtCore.QRect(30, 100, 100, 32))
        self.btn_schedule.setStyleSheet("background-color:rgb(0, 0, 165);\n"
"border-radius: 10px;\n"
"color:rgb(255, 255, 255)")
        self.btn_schedule.setObjectName("btn_schedule")
        self.btn_application = QtWidgets.QPushButton(parent=self.page_chucnang)
        self.btn_application.setGeometry(QtCore.QRect(30, 260, 100, 32))
        self.btn_application.setStyleSheet("background-color:rgb(0, 0, 165);\n"
"border-radius: 10px;\n"
"color:rgb(255, 255, 255)")
        self.btn_application.setObjectName("btn_application")
        self.stackedWidget.addWidget(self.page_chucnang)
        self.page_schedule = QtWidgets.QWidget()
        self.page_schedule.setObjectName("page_schedule")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.page_schedule)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.calendar = QtWidgets.QCalendarWidget(parent=self.page_schedule)
        self.calendar.setMinimumSize(QtCore.QSize(400, 300))
        self.calendar.setStyleSheet("\n"
"QCalendarWidget {\n"
"    background-color: #336b87;\n"
"    color: white;\n"
"}\n"
"QCalendarWidget QToolButton {\n"
"    color: white;\n"
"    background-color: #336b87;\n"
"    border: 1px solid #90afc5;\n"
"    border-radius: 3px;\n"
"    padding: 3px;\n"
"    margin: 3px;\n"
"}\n"
"QCalendarWidget QToolButton:hover {\n"
"    background-color: #2c5a73;\n"
"}\n"
"QCalendarWidget QMenu {\n"
"    background-color: #336b87;\n"
"    color: white;\n"
"}\n"
"QCalendarWidget QSpinBox {\n"
"    color: white;\n"
"    background-color: #336b87;\n"
"    selection-background-color: #2c5a73;\n"
"    selection-color: white;\n"
"}\n"
"QCalendarWidget QTableView {\n"
"    background-color: #336b87;\n"
"    alternate-background-color: #2c5a73;\n"
"    selection-background-color: #90afc5;\n"
"    selection-color: white;\n"
"    color: white;\n"
"    outline: none;\n"
"}\n"
"QCalendarWidget QAbstractItemView:enabled {\n"
"    color: white;\n"
"}\n"
"QCalendarWidget QAbstractItemView:disabled {\n"
"    color: #90afc5;\n"
"}\n"
"QCalendarWidget QTableView::item:hover {\n"
"    background-color: #2c5a73;\n"
"}\n"
"QCalendarWidget QTableView::item:selected {\n"
"    background-color: #90afc5;\n"
"}\n"
"/* Style for days of the week */\n"
"QCalendarWidget QWidget#qt_calendar_navigationbar { \n"
"    background-color: #336b87;\n"
"}\n"
"QCalendarWidget QWidget { \n"
"    alternate-background-color: #336b87;\n"
"    color: white;\n"
"}\n"
"         ")
        self.calendar.setObjectName("calendar")
        self.horizontalLayout_2.addWidget(self.calendar)
        self.schedule_widget = QtWidgets.QWidget(parent=self.page_schedule)
        self.schedule_widget.setObjectName("schedule_widget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.schedule_widget)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.date_label = QtWidgets.QLabel(parent=self.schedule_widget)
        self.date_label.setStyleSheet("color: white; font-weight: bold;")
        self.date_label.setObjectName("date_label")
        self.verticalLayout_2.addWidget(self.date_label)
        self.schedule_table = QtWidgets.QTableWidget(parent=self.schedule_widget)
        self.schedule_table.setStyleSheet("\n"
"QTableWidget {\n"
"    background-color: rgb(144, 175, 197);\n"
"    color: black;\n"
"    gridline-color: #2c5a73;\n"
"    border: none;\n"
"}\n"
"\n"
"QTableWidget::item {\n"
"    padding: 8px;\n"
"    border: none;\n"
"}\n"
"\n"
"QTableWidget::item:selected {\n"
"    background-color: #336b87;\n"
"    color: white;\n"
"}\n"
"\n"
"QHeaderView::section {\n"
"    background-color: #336b87;\n"
"    color: white;\n"
"    padding: 10px;\n"
"    border: none;\n"
"    font-weight: bold;\n"
"    text-align: center;\n"
"}\n"
"\n"
"QTableWidget QScrollBar:vertical {\n"
"    background-color: rgb(144, 175, 197);\n"
"    width: 12px;\n"
"    margin: 0px;\n"
"}\n"
"\n"
"QTableWidget QScrollBar::handle:vertical {\n"
"    background-color: #336b87;\n"
"    border-radius: 6px;\n"
"    min-height: 20px;\n"
"}\n"
"\n"
"QTableWidget QScrollBar::add-line:vertical,\n"
"QTableWidget QScrollBar::sub-line:vertical {\n"
"    height: 0px;\n"
"}\n"
"\n"
"QTableWidget QScrollBar:horizontal {\n"
"    background-color: rgb(144, 175, 197);\n"
"    height: 12px;\n"
"    margin: 0px;\n"
"}\n"
"\n"
"QTableWidget QScrollBar::handle:horizontal {\n"
"    background-color: #336b87;\n"
"    border-radius: 6px;\n"
"    min-width: 20px;\n"
"}\n"
"\n"
"QTableWidget QScrollBar::add-line:horizontal,\n"
"QTableWidget QScrollBar::sub-line:horizontal {\n"
"    width: 0px;\n"
"}\n"
"            ")
        self.schedule_table.setObjectName("schedule_table")
        self.schedule_table.setColumnCount(0)
        self.schedule_table.setRowCount(0)
        self.verticalLayout_2.addWidget(self.schedule_table)
        self.horizontalLayout_2.addWidget(self.schedule_widget)
        self.stackedWidget.addWidget(self.page_schedule)
        self.name_header = QtWidgets.QLabel(parent=self.centralwidget)
        self.name_header.setGeometry(QtCore.QRect(0, 0, 591, 51))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.name_header.setFont(font)
        self.name_header.setStyleSheet("background-color:rgb(118, 54, 54);\n"
"border-radius: 10px;\n"
"color:rgb(255, 255, 255)")
        self.name_header.setObjectName("name_header")
        self.btn_chucnang = QtWidgets.QPushButton(parent=self.centralwidget)
        self.btn_chucnang.setGeometry(QtCore.QRect(10, 230, 81, 31))
        self.btn_chucnang.setStyleSheet("background-color:rgb(204, 136, 102);\n"
"border-radius: 10px")
        self.btn_chucnang.setObjectName("btn_chucnang")
        self.btn_lienhe = QtWidgets.QPushButton(parent=self.centralwidget)
        self.btn_lienhe.setGeometry(QtCore.QRect(10, 340, 81, 31))
        self.btn_lienhe.setStyleSheet("background-color:rgb(204, 136, 102);\n"
"border-radius: 10px")
        self.btn_lienhe.setObjectName("btn_lienhe")
        self.btn_caidat = QtWidgets.QPushButton(parent=self.centralwidget)
        self.btn_caidat.setGeometry(QtCore.QRect(10, 460, 81, 31))
        self.btn_caidat.setStyleSheet("background-color:rgb(204, 136, 102);\n"
"border-radius: 10px")
        self.btn_caidat.setObjectName("btn_caidat")
        self.btn_tintuc = QtWidgets.QPushButton(parent=self.centralwidget)
        self.btn_tintuc.setGeometry(QtCore.QRect(10, 140, 81, 31))
        self.btn_tintuc.setStyleSheet("background-color:rgb(204, 136, 102);\n"
"border-radius: 10px")
        self.btn_tintuc.setObjectName("btn_tintuc")
        self.label_17 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_17.setGeometry(QtCore.QRect(30, 420, 41, 31))
        self.label_17.setStyleSheet("border-radius: 10px;")
        self.label_17.setText("")
        self.label_17.setPixmap(QtGui.QPixmap("/Users/pinxun/Documents/MindX/PTA/PTA07/TriCuong/python-app/ui/../img/settings.png"))
        self.label_17.setScaledContents(True)
        self.label_17.setObjectName("label_17")
        self.label_18 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_18.setGeometry(QtCore.QRect(30, 300, 41, 31))
        self.label_18.setText("")
        self.label_18.setPixmap(QtGui.QPixmap("/Users/pinxun/Documents/MindX/PTA/PTA07/TriCuong/python-app/ui/../img/phone-call.png"))
        self.label_18.setScaledContents(True)
        self.label_18.setObjectName("label_18")
        self.label_19 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_19.setGeometry(QtCore.QRect(30, 180, 51, 41))
        self.label_19.setText("")
        self.label_19.setPixmap(QtGui.QPixmap("/Users/pinxun/Documents/MindX/PTA/PTA07/TriCuong/python-app/ui/../img/7216128.png"))
        self.label_19.setScaledContents(True)
        self.label_19.setObjectName("label_19")
        self.label_20 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_20.setGeometry(QtCore.QRect(30, 100, 41, 31))
        font = QtGui.QFont()
        font.setBold(False)
        self.label_20.setFont(font)
        self.label_20.setMouseTracking(False)
        self.label_20.setTabletTracking(False)
        self.label_20.setAutoFillBackground(False)
        self.label_20.setText("")
        self.label_20.setPixmap(QtGui.QPixmap("/Users/pinxun/Documents/MindX/PTA/PTA07/TriCuong/python-app/ui/../img/newspaper.png"))
        self.label_20.setScaledContents(True)
        self.label_20.setWordWrap(False)
        self.label_20.setOpenExternalLinks(False)
        self.label_20.setObjectName("label_20")
        self.btn_caidat_2 = QtWidgets.QPushButton(parent=self.centralwidget)
        self.btn_caidat_2.setGeometry(QtCore.QRect(10, 570, 81, 31))
        self.btn_caidat_2.setStyleSheet("background-color:rgb(204, 136, 102);\n"
"border-radius: 10px")
        self.btn_caidat_2.setObjectName("btn_caidat_2")
        self.label_21 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_21.setGeometry(QtCore.QRect(30, 530, 41, 31))
        self.label_21.setStyleSheet("border-radius: 10px;")
        self.label_21.setText("")
        self.label_21.setPixmap(QtGui.QPixmap("/Users/pinxun/Documents/MindX/PTA/PTA07/TriCuong/python-app/ui/../img/bell-icon.png"))
        self.label_21.setScaledContents(True)
        self.label_21.setObjectName("label_21")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1100, 24))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.stackedWidget.setCurrentIndex(4)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_3.setText(_translate("MainWindow", "[SSV] - Hoãn sự kiện CISS Has Talent 2024 | Delaying CISS Has Talent 2024"))
        self.label_4.setText(_translate("MainWindow", "[SSV] - Ngày Hội Sách Lần 1 Năm Học 2024-2025 | Book Fair 2024-2025"))
        self.label_6.setText(_translate("MainWindow", "[SSV] - Thông Tin Chi Tiết Về \"House Colour Day\" | Information Regarding \"House Colour Day\""))
        self.label_7.setText(_translate("MainWindow", "[SSV] - Show Your House Spirit – Wear Your House Colors! | Thể hiện tinh thần Nhà - Diện Màu của Nhà!"))
        self.label_16.setText(_translate("MainWindow", "[SSV] - Sedbergh Vietnam 2024 Christmas Letter | Thư Giáng Sinh 2024"))
        self.btn_new_application.setText(_translate("MainWindow", "Tạo đơn mới"))
        self.btn_edit_application.setText(_translate("MainWindow", "Sửa đơn"))
        self.btn_delete_application.setText(_translate("MainWindow", "Xóa đơn"))
        self.label_75.setText(_translate("MainWindow", " Lê Hiếu-Giáo Viên chủ nhiệm-Địa lí"))
        self.label_76.setText(_translate("MainWindow", " Phạm Đăng Dung-Ngữ văn"))
        self.label_77.setText(_translate("MainWindow", " Nguyễn Huyền Trang-GDKT-PL"))
        self.label_78.setText(_translate("MainWindow", " Trần An Khang-Sinh học"))
        self.label_79.setText(_translate("MainWindow", "  Lê Kim Anh-Vật lí"))
        self.label_80.setText(_translate("MainWindow", " James Anderson-P.E"))
        self.label_81.setText(_translate("MainWindow", "  Đỗ Minh Tuấn-GDPQ"))
        self.label_82.setText(_translate("MainWindow", "  Emily Williams-Core English"))
        self.label_83.setText(_translate("MainWindow", "  Bùi Thị Lan-Toán"))
        self.label_84.setText(_translate("MainWindow", "  Mai Quốc Duy-Hoá học"))
        self.txt_name.setPlaceholderText(_translate("MainWindow", "Name"))
        self.btn_update_info.setText(_translate("MainWindow", "Save"))
        self.txt_email.setPlaceholderText(_translate("MainWindow", "Mail"))
        self.cb_gender.setItemText(0, _translate("MainWindow", "None"))
        self.cb_gender.setItemText(1, _translate("MainWindow", "Male"))
        self.cb_gender.setItemText(2, _translate("MainWindow", "Female"))
        self.label.setText(_translate("MainWindow", "Hoạt Động hàng ngày"))
        self.label_2.setText(_translate("MainWindow", "Học tập"))
        self.label_5.setText(_translate("MainWindow", "Dịch vụ"))
        self.label_8.setText(_translate("MainWindow", "Khác"))
        self.label_10.setText(_translate("MainWindow", "Điểm danh"))
        self.label_11.setText(_translate("MainWindow", "Đánh giá định kì"))
        self.label_12.setText(_translate("MainWindow", "Đánh giá thường xuyên"))
        self.label_14.setText(_translate("MainWindow", "  Xe buýt"))
        self.label_43.setText(_translate("MainWindow", "Thông tin học sinh"))
        self.label_44.setText(_translate("MainWindow", "Yêu cầu hỗ trợ "))
        self.label_45.setText(_translate("MainWindow", "Đặt lịch"))
        self.label_15.setText(_translate("MainWindow", " Ăn uống"))
        self.btn_schedule.setText(_translate("MainWindow", "Thời khoá biểu"))
        self.btn_application.setText(_translate("MainWindow", "Làm đơn"))
        self.date_label.setText(_translate("MainWindow", "Thời khoá biểu ngày: "))
        self.name_header.setText(_translate("MainWindow", " Cao Bảo Châu"))
        self.btn_chucnang.setText(_translate("MainWindow", "Chức năng"))
        self.btn_lienhe.setText(_translate("MainWindow", "Liên hệ"))
        self.btn_caidat.setText(_translate("MainWindow", "Cài đặt"))
        self.btn_tintuc.setText(_translate("MainWindow", "Tin Tức"))
        self.btn_caidat_2.setText(_translate("MainWindow", "Thông báo"))
