# Form implementation generated from reading ui file '/Users/pinxun/Documents/MindX/PTA/PTA07/FINAL PROJECT/TriCuong/python-app/ui/register.ui'
#
# Created by: PyQt6 UI code generator 6.8.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(903, 659)
        MainWindow.setStyleSheet("background-color:rgb(203, 203, 203)")
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.frame = QtWidgets.QFrame(parent=self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(510, -30, 401, 681))
        font = QtGui.QFont()
        font.setKerning(True)
        self.frame.setFont(font)
        self.frame.setStyleSheet("background-color:rgb(255, 255, 255);\n"
"")
        self.frame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame.setObjectName("frame")
        self.Logoaccount = QtWidgets.QLabel(parent=self.frame)
        self.Logoaccount.setGeometry(QtCore.QRect(50, 110, 311, 71))
        font = QtGui.QFont()
        font.setFamily("Algerian")
        font.setPointSize(22)
        self.Logoaccount.setFont(font)
        self.Logoaccount.setStyleSheet("color: black;")
        self.Logoaccount.setObjectName("Logoaccount")
        self.loginname = QtWidgets.QLineEdit(parent=self.frame)
        self.loginname.setGeometry(QtCore.QRect(50, 200, 261, 51))
        font = QtGui.QFont()
        font.setFamily("SimSun")
        font.setPointSize(-1)
        self.loginname.setFont(font)
        self.loginname.setStyleSheet("border: none;\n"
"    border-bottom: 1px solid #000; /* Black underline */\n"
"    font-size: 14px;\n"
"    padding: 5px;\n"
"color: black;")
        self.loginname.setText("")
        self.loginname.setFrame(False)
        self.loginname.setEchoMode(QtWidgets.QLineEdit.EchoMode.Normal)
        self.loginname.setDragEnabled(False)
        self.loginname.setReadOnly(False)
        self.loginname.setClearButtonEnabled(False)
        self.loginname.setObjectName("loginname")
        self.loginpassword = QtWidgets.QLineEdit(parent=self.frame)
        self.loginpassword.setGeometry(QtCore.QRect(50, 370, 261, 41))
        font = QtGui.QFont()
        font.setFamily("SimSun")
        font.setPointSize(-1)
        self.loginpassword.setFont(font)
        self.loginpassword.setStyleSheet("border: none;\n"
"    border-bottom: 1px solid #000; /* Black underline */\n"
"    font-size: 14px;\n"
"    padding: 5px;\n"
"color: black;")
        self.loginpassword.setText("")
        self.loginpassword.setFrame(False)
        self.loginpassword.setEchoMode(QtWidgets.QLineEdit.EchoMode.Password)
        self.loginpassword.setCursorPosition(0)
        self.loginpassword.setDragEnabled(False)
        self.loginpassword.setReadOnly(False)
        self.loginpassword.setClearButtonEnabled(False)
        self.loginpassword.setObjectName("loginpassword")
        self.Buttonsignup = QtWidgets.QPushButton(parent=self.frame)
        self.Buttonsignup.setGeometry(QtCore.QRect(50, 500, 261, 51))
        self.Buttonsignup.setStyleSheet("background-color: #000; /* Black background */\n"
"    color: #fff; /* White text */\n"
"    font-size: 14px; /* Adjust text size */\n"
"    border: none; /* Remove borders */\n"
"    border-radius: 20px; /* Rounded corners */\n"
"    padding: 10px 20px; /* Add padding for a larger button */\n"
"    text-align: center; /* Center the text */")
        self.Buttonsignup.setObjectName("Buttonsignup")
        self.loginemail = QtWidgets.QLineEdit(parent=self.frame)
        self.loginemail.setGeometry(QtCore.QRect(50, 280, 261, 51))
        font = QtGui.QFont()
        font.setFamily("SimSun")
        font.setPointSize(-1)
        self.loginemail.setFont(font)
        self.loginemail.setStyleSheet("border: none;\n"
"    border-bottom: 1px solid #000; /* Black underline */\n"
"    font-size: 14px;\n"
"    padding: 5px;\n"
"color: black;")
        self.loginemail.setText("")
        self.loginemail.setFrame(False)
        self.loginemail.setEchoMode(QtWidgets.QLineEdit.EchoMode.Normal)
        self.loginemail.setDragEnabled(False)
        self.loginemail.setReadOnly(False)
        self.loginemail.setClearButtonEnabled(False)
        self.loginemail.setObjectName("loginemail")
        self.loginconfirm = QtWidgets.QLineEdit(parent=self.frame)
        self.loginconfirm.setGeometry(QtCore.QRect(50, 440, 261, 41))
        font = QtGui.QFont()
        font.setFamily("SimSun")
        font.setPointSize(-1)
        self.loginconfirm.setFont(font)
        self.loginconfirm.setStyleSheet("border: none;\n"
"    border-bottom: 1px solid #000; /* Black underline */\n"
"    font-size: 14px;\n"
"    padding: 5px;\n"
"color: black;")
        self.loginconfirm.setText("")
        self.loginconfirm.setFrame(False)
        self.loginconfirm.setEchoMode(QtWidgets.QLineEdit.EchoMode.Password)
        self.loginconfirm.setCursorPosition(0)
        self.loginconfirm.setDragEnabled(False)
        self.loginconfirm.setReadOnly(False)
        self.loginconfirm.setClearButtonEnabled(False)
        self.loginconfirm.setObjectName("loginconfirm")
        self.eyebtn = QtWidgets.QPushButton(parent=self.frame)
        self.eyebtn.setGeometry(QtCore.QRect(270, 380, 41, 31))
        self.eyebtn.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("/Users/pinxun/Documents/MindX/PTA/PTA07/FINAL PROJECT/TriCuong/python-app/ui/../img/hidden.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.eyebtn.setIcon(icon)
        self.eyebtn.setObjectName("eyebtn")
        self.eyebtn_2 = QtWidgets.QPushButton(parent=self.frame)
        self.eyebtn_2.setGeometry(QtCore.QRect(270, 450, 41, 31))
        self.eyebtn_2.setText("")
        self.eyebtn_2.setIcon(icon)
        self.eyebtn_2.setObjectName("eyebtn_2")
        self.btn_login = QtWidgets.QPushButton(parent=self.frame)
        self.btn_login.setGeometry(QtCore.QRect(210, 590, 91, 20))
        self.btn_login.setStyleSheet("background: transparent; /* No background */\n"
"    border: none; /* Remove border */\n"
"    color: #666; /* Light gray text color */\n"
"    font-size: 14px; /* Adjust font size as needed */\n"
"    text-align: left; /* Align text to the left */")
        self.btn_login.setObjectName("btn_login")
        self.label = QtWidgets.QLabel(parent=self.frame)
        self.label.setGeometry(QtCore.QRect(60, 590, 141, 16))
        self.label.setStyleSheet("color: black;")
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(80, 170, 351, 331))
        self.label_2.setText("")
        self.label_2.setPixmap(QtGui.QPixmap("/Users/pinxun/Documents/MindX/PTA/PTA07/FINAL PROJECT/TriCuong/python-app/ui/../img/302065e0-36bf-477b-86d3-f71749fd23b1.webp"))
        self.label_2.setScaledContents(True)
        self.label_2.setObjectName("label_2")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 903, 24))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.Logoaccount.setText(_translate("MainWindow", "Create an account"))
        self.loginname.setPlaceholderText(_translate("MainWindow", "Name"))
        self.loginpassword.setPlaceholderText(_translate("MainWindow", "Password"))
        self.Buttonsignup.setText(_translate("MainWindow", "Sign up"))
        self.loginemail.setPlaceholderText(_translate("MainWindow", "Email"))
        self.loginconfirm.setPlaceholderText(_translate("MainWindow", "Confirm Password"))
        self.btn_login.setText(_translate("MainWindow", "Login"))
        self.label.setText(_translate("MainWindow", "Already have account ?"))
