# Form implementation generated from reading ui file '/Users/pinxun/Documents/MindX/PTA/PTA07/TriCuong/python-app/ui/schedule.ui'
#
# Created by: PyQt6 UI code generator 6.8.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(800, 600)
        self.horizontalLayout = QtWidgets.QHBoxLayout(Form)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.calendar = QtWidgets.QCalendarWidget(parent=Form)
        self.calendar.setMinimumSize(QtCore.QSize(400, 300))
        self.calendar.setObjectName("calendar")
        self.horizontalLayout.addWidget(self.calendar)
        self.schedule_widget = QtWidgets.QWidget(parent=Form)
        self.schedule_widget.setObjectName("schedule_widget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.schedule_widget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.date_label = QtWidgets.QLabel(parent=self.schedule_widget)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        self.date_label.setFont(font)
        self.date_label.setObjectName("date_label")
        self.verticalLayout.addWidget(self.date_label)
        self.schedule_table = QtWidgets.QTableWidget(parent=self.schedule_widget)
        self.schedule_table.setColumnCount(5)
        self.schedule_table.setObjectName("schedule_table")
        self.schedule_table.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.schedule_table.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.schedule_table.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.schedule_table.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.schedule_table.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.schedule_table.setHorizontalHeaderItem(4, item)
        self.schedule_table.horizontalHeader().setDefaultSectionSize(120)
        self.verticalLayout.addWidget(self.schedule_table)
        self.horizontalLayout.addWidget(self.schedule_widget)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.date_label.setText(_translate("Form", "Schedule for: "))
        item = self.schedule_table.horizontalHeaderItem(0)
        item.setText(_translate("Form", "Subject"))
        item = self.schedule_table.horizontalHeaderItem(1)
        item.setText(_translate("Form", "Start Time"))
        item = self.schedule_table.horizontalHeaderItem(2)
        item.setText(_translate("Form", "End Time"))
        item = self.schedule_table.horizontalHeaderItem(3)
        item.setText(_translate("Form", "Teacher"))
        item = self.schedule_table.horizontalHeaderItem(4)
        item.setText(_translate("Form", "Room"))
